# Generated by Django 3.1.3 on 2020-11-25 04:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_auto_20201125_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entry_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
